# This will run tox with https://github.com/coactions/dynamic-matrix
name: tox

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1 # tox, pytest, ansible-lint
  PY_COLORS: 1

jobs:
  pre:
    name: pre
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: Determine matrix
        id: generate_matrix
        uses: coactions/dynamic-matrix@v4
        with:
          skip_explode: 1 # do not generating implicit pyXY jobs
          other_names: |
            py38-2.11-macos:tox -e py38-2.11
            py38-2.11
            py38-2.12
            py38-2.13
            py39-2.11
            py39-2.12
            py39-2.13
            py39-2.14
            py39-2.15
            py310-2.12
            py310-2.13
            py310-2.14
            py310-2.15
            py310-2.16
            py310-2.17
            py311-2.14
            py311-2.15
            py311-2.16
            py311-2.17
            py311-2.18
            py311-devel
            py312-2.16
            py312-2.17
            py312-2.18
            py312-devel
            py313-2.18
            py313-2.18-macos:tox -e py313-2.18
            py313-devel

  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-22.04' }}
    needs: pre
    strategy:
      matrix: ${{ fromJson(needs.pre.outputs.matrix) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.6.9"

      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dev dependencies
        run: uv sync --only-group dev

      - run: PATH=.venv/bin:$PATH ${{ matrix.command }}
